Rails.application.routes.draw do
  get 'sessions/new'
  post 'users/guest_sign_in', to: 'sessions#new_guest'
  get 'signup', to:'users#new'
  get 'statictics',to:'statictics#statictics'
  post '/statictics/up', to: 'statictics#up'
  post '/statictics/down', to: 'statictics#down'
  post 'start/create', to: 'start#create'
  get 'start/:id/edit', to:'start#edit'
  patch 'start/:id/update', to: 'start#update'
  delete '/start/:id/destroy', to: 'start#destroy'
  post 'end/create', to: 'end#create'
  get 'end/:id/edit_memo', to: 'end#edit_memo'
  get 'end/:id/edit', to: 'end#edit'
  patch 'end/:id/update_memo', to: 'end#update_memo'
  patch 'end/:id/update', to: 'end#update'
  get 'contact', to:'home#contact'
  root 'home#home'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
end
